version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management
    expose:
      - '5672'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbit-network

  probot-consumer:
    container_name: consumer
    image: consumer
    #    tty: true
    #    command: tail -F anything
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672'
      QUEUE_NAME: 'probot_queue'
    networks:
      - rabbit-network

  probot-consumer2:
    container_name: consumer-2
    image: consumer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672'
      QUEUE_NAME: 'probot_queue'
    networks:
      - rabbit-network

networks:
  rabbit-network: { }
