FROM rfbrowser:latest
ENV PYTHONUNBUFFERED=1

# Install requirements
RUN python3 -m pip install --upgrade pip && python3 -m pip install robotframework pika

COPY src/consumer.py .
COPY src/executor.py .
CMD ["python3", "consumer.py"]