version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'my-rabbit'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - network
  consumer:
    build: ""
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
    networks:
      - network
networks:
  network: { }