version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management
    expose:
      - '5672'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbit-network

  probot-consumer:
    container_name: consumer
    image: consumer
    #    tty: true
    #    command: tail -F anything
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 1'
    depends_on:
      - rabbitmq
    networks:
      - rabbit-network
    volumes:
      - test-suite-output:/test-output

  probot-consumer2:
    container_name: consumer-2
    image: consumer
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 2'
    networks:
      - rabbit-network
    volumes:
      - test-suite-output:/test-output

  log-combiner:
    container_name: log-combiner
    build: log-combiner
    restart: no
    volumes:
      - test-suite-output:/test-output

networks:
  rabbit-network: { }

volumes:
  test-suite-output: