version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbit-network

  probot-consumer:
    container_name: consumer
    image: consumer:latest
    #    tty: true
    #    command: tail -F anything
    build:
      dockerfile: src/Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 1'
      USING_KUBERNETES: 0
    depends_on:
      - rabbitmq
    ports:
      - "52325:52325"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/test-output
      - ./suites/:/test-suites/

  probot-consumer2:
    container_name: consumer-2
    image: consumer:latest
    #    build:
    #      dockerfile: src/Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 2'
      USING_KUBERNETES: 0
    depends_on:
      - rabbitmq
    ports:
      - "52326:52326"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/test-output
      - ./suites/:/test-suites/

  probot-consumer3:
    container_name: consumer-3
    image: consumer:latest
    #    build:
    #      dockerfile: src/Dockerfile
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 3'
      USING_KUBERNETES: 0
    depends_on:
      - rabbitmq
    ports:
      - "52327:52327"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/test-output
      - ./suites/:/test-suites/

  log-combiner:
    container_name: log-combiner
    image: probot-log-combiner:latest
    build: src/log-combiner
    restart: no
    volumes:
      - test-outputs:/test-output
      - ./docker-output/:/output/

networks:
  rabbit-network: { }

volumes:
  test-outputs: { }