version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbit-network
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  rfbrowser-image-builder:
    container_name: rfbrowser-image-builder
    image: rfbrowser:latest
    build:
      dockerfile: Dockerfile-rfbrowser

  #  rfselenium-image-builder:
  #    container_name: rfselenium-image-builder
  #    image: rfselenium:latest
  #    build:
  #      dockerfile: Dockerfile-rfselenium

  probot-consumer:
    container_name: consumer
    image: consumer:latest
    build:
      dockerfile: Dockerfile-core
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=10&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 1'
      INACTIVITY: '10'
    depends_on:
      - rabbitmq
      - rfbrowser-image-builder
    #      - rfselenium-image-builder
    ports:
      - "52325:52325"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/usr/app/test-output
      - ./suites/:/usr/app/test-suites/

  probot-consumer2:
    container_name: consumer-2
    image: consumer:latest
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=10&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 2'
      INACTIVITY: '10'
    depends_on:
      - rabbitmq
    ports:
      - "52326:52326"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/usr/app/test-output
      - ./suites/:/usr/app/test-suites/

  probot-consumer3:
    container_name: consumer-3
    image: consumer:latest
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=10&retry_delay=5'
      QUEUE_NAME: 'probot_queue'
      EXECUTOR: 'Docker Executor 3'
      INACTIVITY: '10'
    depends_on:
      - rabbitmq
    ports:
      - "52327:52327"
    networks:
      - rabbit-network
    volumes:
      - test-outputs:/usr/app/test-output
      - ./suites/:/usr/app/test-suites/

  log-combiner:
    container_name: log-combiner
    image: log-combiner:latest
    build: src/logcombiner
    restart: no
    volumes:
      - test-outputs:/test-output
      - ./docker-output/:/output/

networks:
  rabbit-network: { }

volumes:
  test-outputs: { }