FROM node:20

RUN apt-get update || : && apt-get install 2to3 -y
RUN apt-get install python3-pip -y

WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install playwright

RUN apt update --fix-missing && apt install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
  libdbus-1-3 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libasound2 ffmpeg --fix-missing

RUN python3 -m pip install --upgrade pip --break-system-packages && python3 -m pip install robotframework-browser --break-system-packages
RUN rfbrowser init

