apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: log-combiner
  name: log-combiner
spec:
  template:
    spec:
      containers:
        - image: log-combiner:latest
          name: log-combiner
          imagePullPolicy: Never
          resources: { }
          volumeMounts:
            # Serve output
            - mountPath: /test-output
              name: test-outputs
            # Put locally
            #        - mountPath: /output
            #          name: output-mount
            - mountPath: /output
              name: output-location
      restartPolicy: OnFailure
      volumes:
        - name: test-outputs
          persistentVolumeClaim:
            claimName: test-outputs
        # Put locally
        #    - name: output-mount
        #      hostPath:
        #        path: /run/desktop/mnt/host/c/users/merel.foekens/pycharmprojects/probot/k8s-output
        #        type: Directory
        # Serve output
        - name: output-location
          persistentVolumeClaim:
            claimName: output-location
status: { }
