apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: probot-consumer
  name: probot-consumer
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: probot-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/probot-rabbit-network: "true"
        io.kompose.service: probot-consumer
    spec:
      containers:
        - env:
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq:5672?connection_attempts=10&retry_delay=5
            - name: EXECUTOR
              value: Kubernetes Executor
            - name: QUEUE_NAME
              value: probot_queue
            - name: INACTIVITY
              value: "10"
          image: consumer:latest
          name: consumer
          imagePullPolicy: Never
          ports:
            - containerPort: 52325
          resources: { }
          volumeMounts:
            - mountPath: /test-output
              name: test-outputs
            - mountPath: /test-suites
              name: test-suites
      initContainers:
        - name: init-requirements
          image: consumer:k8s
          command: [ "/bin/sh", "-c" ]
          args:
            - python3 -m pip install --upgrade pip;
              curl https://raw.githubusercontent.com/mwfoekens/Probot/main/requirements.txt -O;
              python3 -m pip install -r requirements.txt;
        - name: init-browser
          image: consumer:k8s
          command: [ "/bin/sh", "-c" ]
          args:
            - mkdir -p /usr/local/nvm;
              export NVM_DIR=/usr/local/nvm;
              export NODE_VERSION=14.18.1;
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
              |
              bash
              &&
              . /usr/local/nvm/nvm.sh
              &&
              nvm install 14.18.1
              &&
              nvm alias default 14.18.1
              &&
              nvm use default;
              npm --version;
              export NODE_PATH=$NVM_DIR/v$NODE_VERSION/lib/node_modules;
              export PATH=$NVM_DIR/version/node/v$NODE_VERSION/bin:$PATH;
              apt update --fix-missing; apt install -y ibnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libasound2 ffmpeg --fix-missing;
              pyton3 -m pip install robotframework-browser;
              rfbrowser init;
              npm install playwright;
        #          command: [ "export", "NVM_DIR=/usr/local/nvm;", "mkdir", "-p", "$NVM_DIR;" ]
      restartPolicy: Always
      volumes:
        - name: test-outputs
          persistentVolumeClaim:
            claimName: test-outputs
        - name: test-suites
          hostPath:
            path: /run/desktop/mnt/host/c/users/merel.foekens/pycharmprojects/probot/suites
            type: Directory
status: { }
