apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: test-outputs
  name: test-outputs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: { }
